### ISSUE TITLE
You are the hero Gotham needs!

### ISSUE THREAD

**Issue by Coldblackice** [bentasker/RemoveAMP#4]
YES, thank you for creating this. I positively *despise* Google Amp; even years later, I'm still shocked that businesses are cool with Google snatching away user views and click-throughs. It's maddening that it can't be disabled on a per user (or per host) basis.

Thanks for this! Please keep up the heroic work!

**Comment by bentasker** [comment]
Thanks,

Glad to hear others have a need for this, and it's not just me being difficult :)
