### ISSUE TITLE
[Bug] Script doesn't seem to work anymore.

### ISSUE THREAD

**Issue by Izheil** [bentasker/RemoveAMP#6]
The userscript doesn't seem to be working as of lately even on the [test page](https://projectsstatic.bentasker.co.uk/MISC/MISC25/bad.html).

I also tested it [here](https://gamerant-com.cdn.ampproject.org/v/s/gamerant.com/russia-piracy-legal/amp/?usqp=mq331AQKKAFQArABIIACAw%3D%3D&amp_js_v=a9&amp_gsa=1#referrer=https%3A%2F%2Fwww.google.com&csi=0&ampshare=https%3A%2F%2Fgamerant.com%2Frussia-piracy-legal%2F) and it didn't work either.

It seems like the required script that is imported is [this one](https://static1.bentasker.co.uk/adblock/anti-amp/v1.4.3.js#sha384=lNjJABp+iorW1BqUjEM7a/WYaIxB2NyzZJHCmc1Gea1GNi+y++STvz6u7S7LInIP), which doesn't translate the ⚡ right, and instead shows 'âš¡', thing that doesn't happen on the [same script](https://raw.githubusercontent.com/bentasker/RemoveAMP/master/anti-amp.js) from the repo.

Either changing the `@require` tag to `https://raw.githubusercontent.com/bentasker/RemoveAMP/master/anti-amp.js` or changing the conditional line to also check for the attribute "amp-version" to be like the following on the other script would work:

``` JS
if (h[0].getAttribute('amp-version') != null || h[0].getAttribute('amp') != null || h[0].getAttribute('⚡') != null || document.location.href.substr(0,29).toLowerCase() == 'https://www.google.com/amp/s/' ) {
```

**Comment by Izheil** [comment]
Looks like it might have been some misconfiguration on my end, its working now without changes... I'll close this.

**Comment by bentasker** [comment]
Hey,

Thanks for reporting this - I've had a quick check over of delivery just to be safe, and everything looks OK.

> Either changing the @require tag to https://raw.githubusercontent.com/bentasker/RemoveAMP/master/anti-amp.js

Did you try this? Was it in Firefox or Chrome?

The reason I serve via my own CDN is because back when I was setting this all up I found that [Chrome won't run scripts served direct from github](https://projects.bentasker.co.uk/jira_projects/browse/FKAMP-1.html#comment2186433)

> changing the conditional line to also check for the attribute "amp-version" to be like the following on the other script would work

This is a good suggestion, I'm going to look at getting it implemented

**Comment by Izheil** [comment]
I was trying it on Firefox with violentmonkey, not sure why it wasn't working when I opened the issue, but I reseted it to how you have it by default and it worked again, so I assume I might have changed something accidentally when checking it out or something, sorry for the confusion.

As for the @require change yeah, I tested it on Firefox and Vivaldi (which is technically chromium, but maybe Chrome has something more specific about github blocking), and they both work with the direct link from github.

**Comment by bentasker** [comment]
Cool thanks, I'll have to install Chrome again at some point and see if things have changed.

New release: https://github.com/bentasker/RemoveAMP/releases/tag/v1.6 includes the check for `amp-version` though - thanks for the suggestion!
